name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          rm -rf  //Target/Location
          git clone https://github.com/jlaacsohbin/temp.git //Target/Location
          
          
