name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone to File Path
        run: |
          rm -rf  //coreautomation/Tecnomatix/eMServer/SysRoot/Released
          git clone https://github.com/jlaacsohbin/temp.git //coreautomation/Tecnomatix/eMServer/SysRoot/Released
          
          
